# two node (1 worker) cluster config
# Run the comand to create cluster => sudo kind create cluster --name k8s-playground --config kind-multi-node2-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
