# three node (two workers) cluster config
# Run the comand to create cluster => kind create cluster --name k8s-playground --config kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
